package pocketfhir

// Common schema applied to multiple collections
var commonSchema = []map[string]interface{}{
	{"name": "lastUpdated", "type": "date", "required": true},
	{"name": "resource", "type": "json", "options": map[string]interface{}{"maxSize": 5242880}, "required": true},
}

// Common schema applied to multiple collections
var historySchema = []map[string]interface{}{
	{"name": "lastUpdated", "type": "date", "required": true},
	{"name": "fhirId", "type": "text", "required": true},
	{"name": "resource", "type": "json", "options": map[string]interface{}{"maxSize": 5242880}, "required": true},
}

// List of collections
var collections = []map[string]interface{}{
	{"name": "Account", "schema": commonSchema}, {"name": "AccountHistory", "schema": historySchema},
	{"name": "ActivityDefinition", "schema": commonSchema}, {"name": "ActivityDefinitionHistory", "schema": historySchema},
	{"name": "AdministrableProductDefinition", "schema": commonSchema}, {"name": "AdministrableProductDefinitionHistory", "schema": historySchema},
	{"name": "AdverseEvent", "schema": commonSchema}, {"name": "AdverseEventHistory", "schema": historySchema},
	{"name": "AllergyIntolerance", "schema": commonSchema}, {"name": "AllergyIntoleranceHistory", "schema": historySchema},
	{"name": "Appointment", "schema": commonSchema}, {"name": "AppointmentHistory", "schema": historySchema},
	{"name": "AppointmentResponse", "schema": commonSchema}, {"name": "AppointmentResponseHistory", "schema": historySchema},
	{"name": "AuditEvent", "schema": commonSchema}, {"name": "AuditEventHistory", "schema": historySchema},
	{"name": "Basic", "schema": commonSchema}, {"name": "BasicHistory", "schema": historySchema},
	{"name": "Binary", "schema": commonSchema}, {"name": "BinaryHistory", "schema": historySchema},
	{"name": "BiologicallyDerivedProduct", "schema": commonSchema}, {"name": "BiologicallyDerivedProductHistory", "schema": historySchema},
	{"name": "BodyStructure", "schema": commonSchema}, {"name": "BodyStructureHistory", "schema": historySchema},
	{"name": "Bundle", "schema": commonSchema}, {"name": "BundleHistory", "schema": historySchema},
	{"name": "CapabilityStatement", "schema": commonSchema}, {"name": "CapabilityStatementHistory", "schema": historySchema},
	{"name": "CarePlan", "schema": commonSchema}, {"name": "CarePlanHistory", "schema": historySchema},
	{"name": "CareTeam", "schema": commonSchema}, {"name": "CareTeamHistory", "schema": historySchema},
	{"name": "CatalogEntry", "schema": commonSchema}, {"name": "CatalogEntryHistory", "schema": historySchema},
	{"name": "ChargeItem", "schema": commonSchema}, {"name": "ChargeItemHistory", "schema": historySchema},
	{"name": "ChargeItemDefinition", "schema": commonSchema}, {"name": "ChargeItemDefinitionHistory", "schema": historySchema},
	{"name": "Citation", "schema": commonSchema}, {"name": "CitationHistory", "schema": historySchema},
	{"name": "Claim", "schema": commonSchema}, {"name": "ClaimHistory", "schema": historySchema},
	{"name": "ClaimResponse", "schema": commonSchema}, {"name": "ClaimResponseHistory", "schema": historySchema},
	{"name": "ClinicalImpression", "schema": commonSchema}, {"name": "ClinicalImpressionHistory", "schema": historySchema},
	{"name": "ClinicalUseDefinition", "schema": commonSchema}, {"name": "ClinicalUseDefinitionHistory", "schema": historySchema},
	{"name": "CodeSystem", "schema": commonSchema}, {"name": "CodeSystemHistory", "schema": historySchema},
	{"name": "Communication", "schema": commonSchema}, {"name": "CommunicationHistory", "schema": historySchema},
	{"name": "CommunicationRequest", "schema": commonSchema}, {"name": "CommunicationRequestHistory", "schema": historySchema},
	{"name": "CompartmentDefinition", "schema": commonSchema}, {"name": "CompartmentDefinitionHistory", "schema": historySchema},
	{"name": "Composition", "schema": commonSchema}, {"name": "CompositionHistory", "schema": historySchema},
	{"name": "ConceptMap", "schema": commonSchema}, {"name": "ConceptMapHistory", "schema": historySchema},
	{"name": "Condition", "schema": commonSchema}, {"name": "ConditionHistory", "schema": historySchema},
	{"name": "Consent", "schema": commonSchema}, {"name": "ConsentHistory", "schema": historySchema},
	{"name": "Contract", "schema": commonSchema}, {"name": "ContractHistory", "schema": historySchema},
	{"name": "Coverage", "schema": commonSchema}, {"name": "CoverageHistory", "schema": historySchema},
	{"name": "CoverageEligibilityRequest", "schema": commonSchema}, {"name": "CoverageEligibilityRequestHistory", "schema": historySchema},
	{"name": "CoverageEligibilityResponse", "schema": commonSchema}, {"name": "CoverageEligibilityResponseHistory", "schema": historySchema},
	{"name": "DetectedIssue", "schema": commonSchema}, {"name": "DetectedIssueHistory", "schema": historySchema},
	{"name": "Device", "schema": commonSchema}, {"name": "DeviceHistory", "schema": historySchema},
	{"name": "DeviceDefinition", "schema": commonSchema}, {"name": "DeviceDefinitionHistory", "schema": historySchema},
	{"name": "DeviceMetric", "schema": commonSchema}, {"name": "DeviceMetricHistory", "schema": historySchema},
	{"name": "DeviceRequest", "schema": commonSchema}, {"name": "DeviceRequestHistory", "schema": historySchema},
	{"name": "DeviceUseStatement", "schema": commonSchema}, {"name": "DeviceUseStatementHistory", "schema": historySchema},
	{"name": "DiagnosticReport", "schema": commonSchema}, {"name": "DiagnosticReportHistory", "schema": historySchema},
	{"name": "DocumentManifest", "schema": commonSchema}, {"name": "DocumentManifestHistory", "schema": historySchema},
	{"name": "DocumentReference", "schema": commonSchema}, {"name": "DocumentReferenceHistory", "schema": historySchema},
	{"name": "Encounter", "schema": commonSchema}, {"name": "EncounterHistory", "schema": historySchema},
	{"name": "Endpoint", "schema": commonSchema}, {"name": "EndpointHistory", "schema": historySchema},
	{"name": "EnrollmentRequest", "schema": commonSchema}, {"name": "EnrollmentRequestHistory", "schema": historySchema},
	{"name": "EnrollmentResponse", "schema": commonSchema}, {"name": "EnrollmentResponseHistory", "schema": historySchema},
	{"name": "EpisodeOfCare", "schema": commonSchema}, {"name": "EpisodeOfCareHistory", "schema": historySchema},
	{"name": "EventDefinition", "schema": commonSchema}, {"name": "EventDefinitionHistory", "schema": historySchema},
	{"name": "Evidence", "schema": commonSchema}, {"name": "EvidenceHistory", "schema": historySchema},
	{"name": "EvidenceReport", "schema": commonSchema}, {"name": "EvidenceReportHistory", "schema": historySchema},
	{"name": "EvidenceVariable", "schema": commonSchema}, {"name": "EvidenceVariableHistory", "schema": historySchema},
	{"name": "ExampleScenario", "schema": commonSchema}, {"name": "ExampleScenarioHistory", "schema": historySchema},
	{"name": "ExplanationOfBenefit", "schema": commonSchema}, {"name": "ExplanationOfBenefitHistory", "schema": historySchema},
	{"name": "FamilyMemberHistory", "schema": commonSchema}, {"name": "FamilyMemberHistoryHistory", "schema": historySchema},
	{"name": "Flag", "schema": commonSchema}, {"name": "FlagHistory", "schema": historySchema},
	{"name": "Goal", "schema": commonSchema}, {"name": "GoalHistory", "schema": historySchema},
	{"name": "GraphDefinition", "schema": commonSchema}, {"name": "GraphDefinitionHistory", "schema": historySchema},
	{"name": "Group", "schema": commonSchema}, {"name": "GroupHistory", "schema": historySchema},
	{"name": "GuidanceResponse", "schema": commonSchema}, {"name": "GuidanceResponseHistory", "schema": historySchema},
	{"name": "HealthcareService", "schema": commonSchema}, {"name": "HealthcareServiceHistory", "schema": historySchema},
	{"name": "ImagingStudy", "schema": commonSchema}, {"name": "ImagingStudyHistory", "schema": historySchema},
	{"name": "Immunization", "schema": commonSchema}, {"name": "ImmunizationHistory", "schema": historySchema},
	{"name": "ImmunizationEvaluation", "schema": commonSchema}, {"name": "ImmunizationEvaluationHistory", "schema": historySchema},
	{"name": "ImmunizationRecommendation", "schema": commonSchema}, {"name": "ImmunizationRecommendationHistory", "schema": historySchema},
	{"name": "ImplementationGuide", "schema": commonSchema}, {"name": "ImplementationGuideHistory", "schema": historySchema},
	{"name": "Ingredient", "schema": commonSchema}, {"name": "IngredientHistory", "schema": historySchema},
	{"name": "InsurancePlan", "schema": commonSchema}, {"name": "InsurancePlanHistory", "schema": historySchema},
	{"name": "Invoice", "schema": commonSchema}, {"name": "InvoiceHistory", "schema": historySchema},
	{"name": "Library", "schema": commonSchema}, {"name": "LibraryHistory", "schema": historySchema},
	{"name": "Linkage", "schema": commonSchema}, {"name": "LinkageHistory", "schema": historySchema},
	{"name": "List", "schema": commonSchema}, {"name": "ListHistory", "schema": historySchema},
	{"name": "Location", "schema": commonSchema}, {"name": "LocationHistory", "schema": historySchema},
	{"name": "ManufacturedItemDefinition", "schema": commonSchema}, {"name": "ManufacturedItemDefinitionHistory", "schema": historySchema},
	{"name": "Measure", "schema": commonSchema}, {"name": "MeasureHistory", "schema": historySchema},
	{"name": "MeasureReport", "schema": commonSchema}, {"name": "MeasureReportHistory", "schema": historySchema},
	{"name": "Media", "schema": commonSchema}, {"name": "MediaHistory", "schema": historySchema},
	{"name": "Medication", "schema": commonSchema}, {"name": "MedicationHistory", "schema": historySchema},
	{"name": "MedicationAdministration", "schema": commonSchema}, {"name": "MedicationAdministrationHistory", "schema": historySchema},
	{"name": "MedicationDispense", "schema": commonSchema}, {"name": "MedicationDispenseHistory", "schema": historySchema},
	{"name": "MedicationKnowledge", "schema": commonSchema}, {"name": "MedicationKnowledgeHistory", "schema": historySchema},
	{"name": "MedicationRequest", "schema": commonSchema}, {"name": "MedicationRequestHistory", "schema": historySchema},
	{"name": "MedicationStatement", "schema": commonSchema}, {"name": "MedicationStatementHistory", "schema": historySchema},
	{"name": "MedicinalProductDefinition", "schema": commonSchema}, {"name": "MedicinalProductDefinitionHistory", "schema": historySchema},
	{"name": "MessageDefinition", "schema": commonSchema}, {"name": "MessageDefinitionHistory", "schema": historySchema},
	{"name": "MessageHeader", "schema": commonSchema}, {"name": "MessageHeaderHistory", "schema": historySchema},
	{"name": "MolecularSequence", "schema": commonSchema}, {"name": "MolecularSequenceHistory", "schema": historySchema},
	{"name": "NamingSystem", "schema": commonSchema}, {"name": "NamingSystemHistory", "schema": historySchema},
	{"name": "NutritionOrder", "schema": commonSchema}, {"name": "NutritionOrderHistory", "schema": historySchema},
	{"name": "Observation", "schema": commonSchema}, {"name": "ObservationHistory", "schema": historySchema},
	{"name": "ObservationDefinition", "schema": commonSchema}, {"name": "ObservationDefinitionHistory", "schema": historySchema},
	{"name": "OperationDefinition", "schema": commonSchema}, {"name": "OperationDefinitionHistory", "schema": historySchema},
	{"name": "OperationOutcome", "schema": commonSchema}, {"name": "OperationOutcomeHistory", "schema": historySchema},
	{"name": "Organization", "schema": commonSchema}, {"name": "OrganizationHistory", "schema": historySchema},
	{"name": "OrganizationAffiliation", "schema": commonSchema}, {"name": "OrganizationAffiliationHistory", "schema": historySchema},
	{"name": "PackagedProductDefinition", "schema": commonSchema}, {"name": "PackagedProductDefinitionHistory", "schema": historySchema},
	{"name": "Parameters", "schema": commonSchema}, {"name": "ParametersHistory", "schema": historySchema},
	{"name": "Patient", "schema": commonSchema}, {"name": "PatientHistory", "schema": historySchema},
	{"name": "PaymentNotice", "schema": commonSchema}, {"name": "PaymentNoticeHistory", "schema": historySchema},
	{"name": "PaymentReconciliation", "schema": commonSchema}, {"name": "PaymentReconciliationHistory", "schema": historySchema},
	{"name": "Person", "schema": commonSchema}, {"name": "PersonHistory", "schema": historySchema},
	{"name": "PlanDefinition", "schema": commonSchema}, {"name": "PlanDefinitionHistory", "schema": historySchema},
	{"name": "Practitioner", "schema": commonSchema}, {"name": "PractitionerHistory", "schema": historySchema},
	{"name": "PractitionerRole", "schema": commonSchema}, {"name": "PractitionerRoleHistory", "schema": historySchema},
	{"name": "Procedure", "schema": commonSchema}, {"name": "ProcedureHistory", "schema": historySchema},
	{"name": "Provenance", "schema": commonSchema}, {"name": "ProvenanceHistory", "schema": historySchema},
	{"name": "Questionnaire", "schema": commonSchema}, {"name": "QuestionnaireHistory", "schema": historySchema},
	{"name": "QuestionnaireResponse", "schema": commonSchema}, {"name": "QuestionnaireResponseHistory", "schema": historySchema},
	{"name": "RegulatedAuthorization", "schema": commonSchema}, {"name": "RegulatedAuthorizationHistory", "schema": historySchema},
	{"name": "RelatedPerson", "schema": commonSchema}, {"name": "RelatedPersonHistory", "schema": historySchema},
	{"name": "RequestGroup", "schema": commonSchema}, {"name": "RequestGroupHistory", "schema": historySchema},
	{"name": "ResearchDefinition", "schema": commonSchema}, {"name": "ResearchDefinitionHistory", "schema": historySchema},
	{"name": "ResearchElementDefinition", "schema": commonSchema}, {"name": "ResearchElementDefinitionHistory", "schema": historySchema},
	{"name": "ResearchStudy", "schema": commonSchema}, {"name": "ResearchStudyHistory", "schema": historySchema},
	{"name": "ResearchSubject", "schema": commonSchema}, {"name": "ResearchSubjectHistory", "schema": historySchema},
	{"name": "RiskAssessment", "schema": commonSchema}, {"name": "RiskAssessmentHistory", "schema": historySchema},
	{"name": "Schedule", "schema": commonSchema}, {"name": "ScheduleHistory", "schema": historySchema},
	{"name": "SearchParameter", "schema": commonSchema}, {"name": "SearchParameterHistory", "schema": historySchema},
	{"name": "ServiceRequest", "schema": commonSchema}, {"name": "ServiceRequestHistory", "schema": historySchema},
	{"name": "Slot", "schema": commonSchema}, {"name": "SlotHistory", "schema": historySchema},
	{"name": "Specimen", "schema": commonSchema}, {"name": "SpecimenHistory", "schema": historySchema},
	{"name": "SpecimenDefinition", "schema": commonSchema}, {"name": "SpecimenDefinitionHistory", "schema": historySchema},
	{"name": "StructureDefinition", "schema": commonSchema}, {"name": "StructureDefinitionHistory", "schema": historySchema},
	{"name": "StructureMap", "schema": commonSchema}, {"name": "StructureMapHistory", "schema": historySchema},
	{"name": "Subscription", "schema": commonSchema}, {"name": "SubscriptionHistory", "schema": historySchema},
	{"name": "SubscriptionStatus", "schema": commonSchema}, {"name": "SubscriptionStatusHistory", "schema": historySchema},
	{"name": "SubscriptionTopic", "schema": commonSchema}, {"name": "SubscriptionTopicHistory", "schema": historySchema},
	{"name": "Substance", "schema": commonSchema}, {"name": "SubstanceHistory", "schema": historySchema},
	{"name": "SubstanceDefinition", "schema": commonSchema}, {"name": "SubstanceDefinitionHistory", "schema": historySchema},
	{"name": "SupplyDelivery", "schema": commonSchema}, {"name": "SupplyDeliveryHistory", "schema": historySchema},
	{"name": "SupplyRequest", "schema": commonSchema}, {"name": "SupplyRequestHistory", "schema": historySchema},
	{"name": "Task", "schema": commonSchema}, {"name": "TaskHistory", "schema": historySchema},
	{"name": "TerminologyCapabilities", "schema": commonSchema}, {"name": "TerminologyCapabilitiesHistory", "schema": historySchema},
	{"name": "TestReport", "schema": commonSchema}, {"name": "TestReportHistory", "schema": historySchema},
	{"name": "TestScript", "schema": commonSchema}, {"name": "TestScriptHistory", "schema": historySchema},
	{"name": "ValueSet", "schema": commonSchema}, {"name": "ValueSetHistory", "schema": historySchema},
	{"name": "VerificationResult", "schema": commonSchema}, {"name": "VerificationResultHistory", "schema": historySchema},
	{"name": "VisionPrescription", "schema": commonSchema}, {"name": "VisionPrescriptionHistory", "schema": historySchema},
}
